Lab second main
Galagadiv/purshak-illya-IPZ-32 pull request #2
Opened 2024-09-11 08:25 UTC by Galagadiv

2024-09-17 11:24 UTC, vozniuk-lntu requested changes
1. width: 1600px; оце прибери
2. зробити кольори через змінні
3. передивитись всю типографію елементів
4. пропиши атрибути ширина і висота всім картинкам, як у фігмі. І перевір чи прописаний всюди alt

Tip: Always specify both the height and width attributes for images. If height and width are set, the space required for the image is reserved when the page is loaded. However, without these attributes, the browser does not know the size of the image, and cannot reserve the appropriate space to it.

5. у портфоліо одна секція з двома списками (кнопки і карточки)

2024-09-17 11:24 UTC, vozniuk-lntu commented on css/styles.css
> +	text-decoration: none;
text-decoration: none; тільки для ссилки
font-family: "Roboto", sans-serif; оце на body

2024-09-17 11:24 UTC, vozniuk-lntu commented on css/styles.css
> +	height: 80px;
висоту прибери

2024-09-17 11:24 UTC, vozniuk-lntu commented on portfolio.html
> +		<header class="highline">
оце header клас

2024-09-17 11:24 UTC, vozniuk-lntu commented on index.html
> +			<section class="header">
це клас hero

2024-09-17 11:24 UTC, vozniuk-lntu commented on index.html
>  				<h1>ЕФЕКТИВНІ РІШЕННЯ ДЛЯ<br />ВАШОГО БІЗНЕСУ</h1>
не заданий шрифт заголовка

2024-09-17 21:15 UTC, Galagadiv commented on index.html
>  				<h1>ЕФЕКТИВНІ РІШЕННЯ ДЛЯ<br />ВАШОГО БІЗНЕСУ</h1>
done

2024-09-17 21:15 UTC, Galagadiv commented on index.html
> +			<section class="header">
done

2024-09-17 21:16 UTC, Galagadiv commented on portfolio.html
> +		<header class="highline">
done

2024-09-18 07:29 UTC, vozniuk-lntu commented
1. колір контактних посилань в хедері
2. special виправити заголовки на h3, можеш додати прихований h2
3. whatDoing там заголовок h2
4. team "Наша команда" це h2, а імена розробників h3
5. letter-spacing переробити на em

2024-09-18 07:30 UTC, vozniuk-lntu approved these changes
https://docs.google.com/document/d/1Oeay7NWz9ltQyIij00fH-GLMeKd0Hec0/edit?usp=drive_link&ouid=104518963218417128491&rtpof=true&sd=true

2024-09-18 07:30 UTC, vozniuk-lntu commented on portfolio.html
>  						<img src="./images/portfolio/techno.jpg" alt="" />
розміри картинкам пропиши

2024-09-18 07:33 UTC, merged